/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_dv;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Dv_7 extends javax.swing.JFrame {

    static ArrayList miunidad = new ArrayList();
    static ArrayList favoritos = new ArrayList();
    static ArrayList papelera = new ArrayList();
    static ArrayList<Archivos> archivos = new ArrayList();
    static ArrayList<Carpetas> carpetas = new ArrayList();
    static Random random = new Random();

    /**
     * Creates new form Dv_7
     */
    public Dv_7() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sp_tamaño = new javax.swing.JSpinner();
        cb_extension = new javax.swing.JComboBox<>();
        tf_nomarchivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nomcarpeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ar_a_cp = new javax.swing.JFrame();
        cb_carpetas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cp_a_cp = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        cb_carp1 = new javax.swing.JComboBox<>();
        cb_carp2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        menu_unidad = new javax.swing.JPopupMenu();
        Fav = new javax.swing.JMenuItem();
        elim = new javax.swing.JMenuItem();
        Descargar = new javax.swing.JMenuItem();
        menu_papelera = new javax.swing.JPopupMenu();
        elim_def = new javax.swing.JMenuItem();
        restaurar = new javax.swing.JMenuItem();
        menu_fav = new javax.swing.JPopupMenu();
        Elim_fav = new javax.swing.JMenuItem();
        descarga = new javax.swing.JFrame();
        pb_hilo1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_carpetas = new javax.swing.JList<>();
        pb_descarga = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_descarga = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Mi_unidad = new javax.swing.JMenuItem();
        Favoritos = new javax.swing.JMenuItem();
        Papelera = new javax.swing.JMenuItem();
        Agregar = new javax.swing.JMenuItem();

        jLabel1.setText("Agregar");

        jLabel2.setText("Agregar archivo");

        jLabel3.setText("Agregar carpeta");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Extension:");

        jLabel6.setText("Tamaño:");

        cb_extension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".pdf", ".txt", ".docx", ".jpg", ".mp4" }));

        jLabel7.setText("Nombre:");

        jButton1.setText("Agregar archivo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("Agregar carpeta a carpeta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Agregar a carpeta");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton6.setText("Finalizar carpeta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_nomcarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_extension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_nomarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addGap(93, 93, 93))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(62, 62, 62))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(287, 287, 287))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addComponent(tf_nomcarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_nomarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_extension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sp_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel8.setText("Agregue a una carpeta:");

        jButton5.setText("Agregar a carpeta");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ar_a_cpLayout = new javax.swing.GroupLayout(ar_a_cp.getContentPane());
        ar_a_cp.getContentPane().setLayout(ar_a_cpLayout);
        ar_a_cpLayout.setHorizontalGroup(
            ar_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ar_a_cpLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(45, 45, 45)
                .addComponent(cb_carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(ar_a_cpLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ar_a_cpLayout.setVerticalGroup(
            ar_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ar_a_cpLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ar_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton5)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel10.setText("Esta es la carpeta que usted elige");

        jButton8.setText("Agregar a carpeta");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel9.setText("En esta carpeta usted la mete");

        javax.swing.GroupLayout cp_a_cpLayout = new javax.swing.GroupLayout(cp_a_cp.getContentPane());
        cp_a_cp.getContentPane().setLayout(cp_a_cpLayout);
        cp_a_cpLayout.setHorizontalGroup(
            cp_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cp_a_cpLayout.createSequentialGroup()
                .addGroup(cp_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cp_a_cpLayout.createSequentialGroup()
                        .addComponent(cb_carp1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_carp2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cp_a_cpLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cp_a_cpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
        );
        cp_a_cpLayout.setVerticalGroup(
            cp_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cp_a_cpLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(cp_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cp_a_cpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_carp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        Fav.setText("Agregar a favoritos");
        Fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavActionPerformed(evt);
            }
        });
        menu_unidad.add(Fav);

        elim.setText("Eliminar");
        elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimActionPerformed(evt);
            }
        });
        menu_unidad.add(elim);

        Descargar.setText("Descargar");
        Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarActionPerformed(evt);
            }
        });
        menu_unidad.add(Descargar);

        elim_def.setText("Destruir");
        elim_def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elim_defActionPerformed(evt);
            }
        });
        menu_papelera.add(elim_def);

        restaurar.setText("Restaurar");
        restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarActionPerformed(evt);
            }
        });
        menu_papelera.add(restaurar);

        Elim_fav.setText("Eliminar");
        Elim_fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elim_favActionPerformed(evt);
            }
        });
        menu_fav.add(Elim_fav);

        javax.swing.GroupLayout descargaLayout = new javax.swing.GroupLayout(descarga.getContentPane());
        descarga.getContentPane().setLayout(descargaLayout);
        descargaLayout.setHorizontalGroup(
            descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        descargaLayout.setVerticalGroup(
            descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pb_hilo1.setName(""); // NOI18N
        pb_hilo1.setString("");
        pb_hilo1.setStringPainted(true);

        jl_carpetas.setModel(new DefaultListModel());
        jl_carpetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_carpetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_carpetas);

        jt_descarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Exrension", "Link", "Tamaño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_descarga);

        jMenu1.setText("File");

        Mi_unidad.setText("Mi unidad");
        Mi_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_unidadActionPerformed(evt);
            }
        });
        jMenu1.add(Mi_unidad);

        Favoritos.setText("Favoritos");
        Favoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritosActionPerformed(evt);
            }
        });
        jMenu1.add(Favoritos);

        Papelera.setText("Papelera");
        Papelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapeleraActionPerformed(evt);
            }
        });
        jMenu1.add(Papelera);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jMenu1.add(Agregar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pb_hilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(pb_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_hilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritosActionPerformed
        // TODO add your handling code here:
        pb_hilo1.setString("Favoritos");
        adminfav af = new adminfav("./favoritos.dbvd");
        af.cargarArchivo();
        DefaultListModel model = new DefaultListModel();
        for (Object f : af.getFavoritos()) {
            model.addElement(f);
        }
        jl_carpetas.setModel(model);
    }//GEN-LAST:event_FavoritosActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        jFrame1.pack();
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setVisible(true);
        pb_hilo1.setString("Agregar");
    }//GEN-LAST:event_AgregarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            adminunidad au = new adminunidad("./Unidad.dbvd");
            au.cargarArchivo();
            adminarchivos av = new adminarchivos("./archivos.dbvd");
            String nombre = tf_nomarchivo.getText();
            int tamaño = (int) sp_tamaño.getValue();
            String extension = cb_extension.getSelectedItem().toString();
            String link = "dive.google.com/";
            for (int i = 0; i < 10; i++) {
                if (i == 2 || i == 5 || i == 8) {
                    link += (char) (97 + random.nextInt(26));
                } else if (i == 0 || i == 3 || i == 6 || i == 9) {
                    link += (char) (65 + random.nextInt(26));
                } else {
                    link += (char) (48 + random.nextInt(10));
                } // Fin If
            }
            System.out.println(link);
            Archivos x = new Archivos(nombre, link, extension, tamaño);
            au.getUnidad().add(x);
            au.escribirArchivo();
            av.getalistaarchivos().add(x);
            av.escribirArchivo();
            JOptionPane.showMessageDialog(null, "Agregado con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        admincarpetas ac = new admincarpetas("./carpetas.dbvd");
        ac.cargarArchivo();
        ar_a_cp.pack();
        ar_a_cp.setLocationRelativeTo(null);
        ar_a_cp.setVisible(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel(ac.getListacarpetas().toArray());
        cb_carpetas.setModel(model);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
              adminunidad au = new adminunidad("./Unidad.dbvd");
                au.cargarArchivo();
                admincarpetas ac = new admincarpetas("./carpetas.dbvd");
                ac.cargarArchivo();
                Carpetas c = (Carpetas) cb_carpetas.getSelectedItem();
                adminarchivos av = new adminarchivos("./archivos.dbvd");
                av.cargarArchivo();
            if (ac.getListacarpetas().size() > 0) { 
                String nombre = tf_nomarchivo.getText();
                int tamaño = (int) sp_tamaño.getValue();
                String extension = cb_extension.getSelectedItem().toString();
                String link = "dive.google.com/" + c.getNombre() + "/";

                for (int i = 0; i < 10; i++) {
                    if (i == 2 || i == 5 || i == 8) {
                        link += (char) (97 + random.nextInt(26));
                    } else if (i == 0 || i == 3 || i == 6 || i == 9) {
                        link += (char) (65 + random.nextInt(26));
                    } else {
                        link += (char) (48 + random.nextInt(10));
                    }
                }
                System.out.println(link);
                Archivos x = new Archivos(nombre, link, extension, tamaño);
                av.getalistaarchivos().add(x);
                av.escribirArchivo();
                c.getArchivos().add(x);
                ac.getListacarpetas().add(c);
                ac.escribirArchivo();
                au.getUnidad().add(c);
                au.escribirArchivo();
                ar_a_cp.setVisible(false);
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                
            } else {
                JOptionPane.showMessageDialog(null, "Lo sentimos pero no hay carpetas creadas ");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        try {
            admincarpetas ac = new admincarpetas("./carpetas.dbvd");
            ac.cargarArchivo();
            Carpetas c1, c2;
            c1 = (Carpetas) cb_carp1.getSelectedItem();
            c2 = (Carpetas) cb_carp2.getSelectedItem();
            c1.setLink("dive.google.com/" + c2.getNombre() + c1.getLink().substring(14, 24));
            c2.getCarpetas().add(c1);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(null, "Agregado con exito");
            cp_a_cp.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            adminunidad au = new adminunidad("./Unidad.dbvd");
            au.cargarArchivo();
            admincarpetas ac = new admincarpetas("./carpetas.dbvd");
            ac.cargarArchivo();
            String nombre = tf_nomcarpeta.getText();
            String link = "dive.google.com/";
            for (int i = 0; i < 5; i++) {
                if (i == 2 || i == 4) {
                    link += (char) (97 + random.nextInt(26));
                } else if (i == 0 || i == 3 || i == 1) {
                    link += (char) (65 + random.nextInt(26));
                } else {
                    link += (char) (48 + random.nextInt(10));
                }
            }
            Carpetas c = new Carpetas(nombre, link);
            ac.getListacarpetas().add(c);
            ac.escribirArchivo();
            au.getUnidad().add(c);
            au.escribirArchivo();
            JOptionPane.showMessageDialog(null, "Agregado con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        admincarpetas ac = new admincarpetas("./carpetas.dbvd");
        ac.cargarArchivo();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Carpetas c : ac.getListacarpetas()) {
          model.addElement(c);
        }
        cb_carp1.setModel(model);
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(ac.getListacarpetas().toArray());
         for (Carpetas c : ac.getListacarpetas()) {
          model2.addElement(c);
        }
        cb_carp2.setModel(model2);

        cp_a_cp.pack();
        cp_a_cp.setLocationRelativeTo(null);
        cp_a_cp.setVisible(true);
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void Mi_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_unidadActionPerformed
        // TODO add your handling code here:
        pb_hilo1.setString("Mi unidad");
        DefaultListModel model = new DefaultListModel();
        adminunidad au = new adminunidad("./Unidad.dbvd");
        au.cargarArchivo();
        for (Object a : au.getUnidad()) {
            model.addElement(a);
        }

        jl_carpetas.setModel(model);
    }//GEN-LAST:event_Mi_unidadActionPerformed

    private void jl_carpetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_carpetasMouseClicked
        // TODO add your handling code here:
        if (jl_carpetas.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                if (pb_hilo1.getString().equals("Mi unidad")) {
                    menu_unidad.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                } else if (pb_hilo1.getString().equals("Papelera")) {
                    menu_papelera.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                } else if (pb_hilo1.getString().equals("Favoritos")) {
                    menu_fav.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                }

            }
        }
    }//GEN-LAST:event_jl_carpetasMouseClicked

    private void FavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) jl_carpetas.getModel();
        adminfav af = new adminfav("./favoritos.dbvd");
        af.cargarArchivo();
        Object o = modelo.getElementAt(jl_carpetas.getSelectedIndex());
        if (jl_carpetas.getSelectedIndex() >= 0) {
            af.getFavoritos().add(o);
            af.escribirArchivo();
            modelo.remove(jl_carpetas.getSelectedIndex());

        }
        jl_carpetas.setModel(modelo);
    }//GEN-LAST:event_FavActionPerformed

    private void elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimActionPerformed
        // TODO add your handling code here:
        adminunidad au = new adminunidad("./Unidad.dbvd");
        au.cargarArchivo();
        DefaultListModel modelo
                = (DefaultListModel) jl_carpetas.getModel();
        adminpapelera ap = new adminpapelera("./papelera.dbvd");
        ap.cargarArchivo();
        Object o = modelo.getElementAt(jl_carpetas.getSelectedIndex());
        if (jl_carpetas.getSelectedIndex() >= 0) {
            au.getUnidad().remove(jl_carpetas.getSelectedIndex());
            au.escribirArchivo();
            ap.getPapelera().add(o);
            ap.escribirArchivo();
            modelo.remove(jl_carpetas.getSelectedIndex());

        }
        jl_carpetas.setModel(modelo);
    }//GEN-LAST:event_elimActionPerformed

    private void PapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapeleraActionPerformed
        // TODO add your handling code here:
        pb_hilo1.setString("Papelera");
        adminpapelera ap = new adminpapelera("./papelera.dbvd");
        ap.cargarArchivo();
        DefaultListModel model = new DefaultListModel();
        for (Object f : ap.getPapelera()) {
            model.addElement(f);
        }
        jl_carpetas.setModel(model);
    }//GEN-LAST:event_PapeleraActionPerformed

    private void restaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarActionPerformed
        // TODO add your handling code here:
        try {
            adminunidad au = new adminunidad("./Unidad.dbvd");
            au.cargarArchivo();
            DefaultListModel modelo
                    = (DefaultListModel) jl_carpetas.getModel();
            adminpapelera ap = new adminpapelera("./papelera.dbvd");
            ap.cargarArchivo();
            if (jl_carpetas.getSelectedIndex() >= 0) {
                au.getUnidad().add(modelo.getElementAt(jl_carpetas.getSelectedIndex()));
                au.escribirArchivo();
                ap.getPapelera().remove(jl_carpetas.getSelectedIndex());
                ap.escribirArchivo();
                modelo.remove(jl_carpetas.getSelectedIndex());

            }
            JOptionPane.showMessageDialog(null, "Se restauro con exito en su unidad");
            jl_carpetas.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_restaurarActionPerformed

    private void elim_defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elim_defActionPerformed
        // TODO add your handling code here:
        try {
            DefaultListModel modelo
                    = (DefaultListModel) jl_carpetas.getModel();
            adminpapelera ap = new adminpapelera("./papelera.dbvd");
            ap.cargarArchivo();
            if (jl_carpetas.getSelectedIndex() >= 0) {
                ap.getPapelera().remove(jl_carpetas.getSelectedIndex());
                ap.escribirArchivo();
                modelo.remove(jl_carpetas.getSelectedIndex());

            }
            JOptionPane.showMessageDialog(null, "Se destruyo con exito");
            jl_carpetas.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_elim_defActionPerformed

    private void Elim_favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elim_favActionPerformed
        // TODO add your handling code here:
        adminfav af = new adminfav("./favoritos.dbvd");
        af.cargarArchivo();
        DefaultListModel modelo
                = (DefaultListModel) jl_carpetas.getModel();
        adminpapelera ap = new adminpapelera("./papelera.dbvd");
        ap.cargarArchivo();
        Object o = modelo.getElementAt(jl_carpetas.getSelectedIndex());
        if (jl_carpetas.getSelectedIndex() >= 0) {
            af.getFavoritos().remove(jl_carpetas.getSelectedIndex());
            af.escribirArchivo();
            ap.getPapelera().add(o);
            ap.escribirArchivo();
            modelo.remove(jl_carpetas.getSelectedIndex());

        }
        jl_carpetas.setModel(modelo);
    }//GEN-LAST:event_Elim_favActionPerformed

    private void DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) jl_carpetas.getModel();
        adminunidad au = new adminunidad("./Unidad.dbvd");
            au.cargarArchivo();
        if (jl_carpetas.getSelectedIndex() >= 0) {
            if (modelo.getElementAt(jl_carpetas.getSelectedIndex()) instanceof Carpetas) {
                int acum=0;
                int tiempo;
                for (Archivos o :((Carpetas)au.getUnidad().get(jl_carpetas.getSelectedIndex())).getArchivos() ) {
                    acum+=o.getTamaño();
                }
                System.out.println(acum);
                tiempo=acum / 10;
                hilo_descargar hd = new hilo_descargar(pb_descarga,10, jt_descarga,(Carpetas)au.getUnidad().get(jl_carpetas.getSelectedIndex()));
                Thread proceso1 = new Thread(hd);
                proceso1.start();
            }else{
            JOptionPane.showMessageDialog(null, "No es una carpeta");
            }
        }

    }//GEN-LAST:event_DescargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dv_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dv_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dv_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dv_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dv_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Descargar;
    private javax.swing.JMenuItem Elim_fav;
    private javax.swing.JMenuItem Fav;
    private javax.swing.JMenuItem Favoritos;
    private javax.swing.JMenuItem Mi_unidad;
    private javax.swing.JMenuItem Papelera;
    private javax.swing.JFrame ar_a_cp;
    private javax.swing.JComboBox<String> cb_carp1;
    private javax.swing.JComboBox<String> cb_carp2;
    private javax.swing.JComboBox<String> cb_carpetas;
    private javax.swing.JComboBox<String> cb_extension;
    private javax.swing.JFrame cp_a_cp;
    private javax.swing.JFrame descarga;
    private javax.swing.JMenuItem elim;
    private javax.swing.JMenuItem elim_def;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jl_carpetas;
    private javax.swing.JTable jt_descarga;
    private javax.swing.JPopupMenu menu_fav;
    private javax.swing.JPopupMenu menu_papelera;
    private javax.swing.JPopupMenu menu_unidad;
    private javax.swing.JProgressBar pb_descarga;
    private javax.swing.JProgressBar pb_hilo1;
    private javax.swing.JMenuItem restaurar;
    private javax.swing.JSpinner sp_tamaño;
    private javax.swing.JTextField tf_nomarchivo;
    private javax.swing.JTextField tf_nomcarpeta;
    // End of variables declaration//GEN-END:variables
}
